packages:
  common:
    component: com.example.multiModule
    postgres:
      entity: com.example.multiModule.common.spring.postgres.entities
      repository: com.example.multiModule.common.spring.postgres.repositories
    mongo:
      entity: com.example.multiModule.common.spring.mongo.entities
      repository: com.example.multiModule.common.spring.mongo.repositories
    neo4j:
      entity: com.example.multiModule.common.spring.neo4j.entities
      repository: com.example.multiModule.common.spring.neo4j.repositories

spring:
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2 # Default: Same as maximum-pool-size
      maximum-pool-size: 4 # Default: 10
      idle-timeout: 60000 # Default: 60seconds
      connection-timeout: 30000 # Default: 30000
      leak-detection-threshold: 5000 #5sec Default: 0 -> disable
      max-lifetime: 600000 # 10min, Default: 1800000 (30 minutes)
