app:
  packages: com.example.multiModule.sampleDbAccess
spring:
  datasource:
    postgres:
      host: localhost
      port: 5433
      database: postgres
      username: postgres
      password: postgres
    mongo:
      host: localhost
      port: 27018
      database: mongo
    neo4j:
      host: localhost
      port: 7474
      database: neo4j
      username: neo4j
      password: test
    cassandra:
      host: localhost
      port: 9042
      database: cassandra
      username: cassandra
      password: test
  profiles:
    include: common
  jpa:
    postgres:
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: false
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
