app:
  packages: com.example.multiModule.sampleDbAccess
spring:
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: postgres
    mongo:
      host: localhost
      port: 27018
      database: mongo
    neo4j:
      host: localhost
      port: 7474
      database: neo4j
      username: neo4j
      password: test
  profiles:
    include: common
  jpa:
    postgres:
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: false
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
