version: '3.1'

services:
  neo4j:
    image: neo4j
    container_name: "neo4j"
    #restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/multyBasetest
    volumes:
      - neo4j_data:/data

  mongo:
    image: mongo
    container_name: "mongo"
    #restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

  postgresql:
    image: postgres
    container_name: "postgresql"
    #restart: always
    ports:
      - 5433:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  postgresql:
    external: false
  mongodb:
    external: false
  neo4j_data:
    external: false
