CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	login VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	fio VARCHAR(255) NOT NULL,
	mobile_phone VARCHAR(20),
	news_ids VARCHAR(255)[]
)